### ISSUE TITLE
'Fails provision request' Error when trying to add external collection to wix site

### ISSUE THREAD

**Issue by rkpoore** [wix/corvid-external-db-mysql-adapter#17]
I have followed the instructions, including the SQL_CONFIG setup, but when I try to connect to the external database from wix I get the following error ...

"Unable to fetch result (Connector with namespace 'wixtest' and instanceId 'b6fa1942-76ef-4b08-b19d-9adc66ad4341' fails provision request)"

**Comment by evgolsh** [comment]
Did you set the SECRET_KEY env variable?

**Comment by rkpoore** [comment]
Yes, I did use the SECRET_KEY variable. I had the same problem when I tried the using the Firestore Adapter (for which I had also set the SECRET_KEY var)

**Comment by ebaynash** [comment]
I had the same issue. Try the following  style of connection string using the port:
{ "host":"myDBServerIP", 
 "port":3306,
 "user":"myUser",
 "password":"myPassword",
 "database":"myDatabase"}

**Comment by AmirTugi** [comment]
Hey guys, after a lot of searching I found out that you need to connect the cloud-run instance to the cloud SQL app using [this guide](https://cloud.google.com/sql/docs/mysql/connect-run#configuring).

After doing this simple connection - everything worked.

🥳

**Comment by happyappledog** [comment]
I had this problem before and it took me a day to figure it out ... 

Make sure SQL_CONFIG is correct and in the right format. This is what I have `  SQL_CONFIG: '{"host": "xxx", "user": "xxx", "password" : "xxx", "port": "xxx", "database" : "xxx"}'` **in one line**

when connecting to the external database from wix, a provision request is sent, so you can also try sending the provision request in Postman directly to your endpoint, see if it succeeds.

**Comment by eboulis** [comment]
Hi Guys,

Having followed all of the above and implemented changes as described, I am still having the same please help

I have tried both of the following and they do not work:
SQL_CONFIG        {"host":"xxx.xxx.xxx.xxx", "port":"xxxx",  "user":"xxxx", "password":"xxxxx", "database":"xxxx"}
and 
SQL_CONFIG                      {"socketPath":"/cloudsql/ptwebdb",  "user":"xxxx", "password":"xxxxx", "database":"xxxx"} 

Here are my remaining environment variables which I used:
SECRET_KEY                      "xxxxx" 
ALLOWED_OPERATIONS  {"provision", "get", "find", "count", "update", "insert", "remove", "select", "delete", "describeDatabase", "finditem", "findSchemas", "listSchemas", "list", "convert", "load", "listbuilds"} 

The container runs on Google Cloud Run, the MySQL database runs on Google SQL Cloud fully managed service, database is working fine and database user has all permissions.

Any help you can provide is much appreciated.

Regards,

Eugene Boulis

**Comment by happyappledog** [comment]
> Hi Guys,
> 
> Having followed all of the above and implemented changes as described, I am still having the same please help
> 
> I have tried both of the following and they do not work:
> SQL_CONFIG {"host":"xxx.xxx.xxx.xxx", "port":"xxxx", "user":"xxxx", "password":"xxxxx", "database":"xxxx"}
> and
> SQL_CONFIG {"socketPath":"/cloudsql/ptwebdb", "user":"xxxx", "password":"xxxxx", "database":"xxxx"}
> 
> Here are my remaining environment variables which I used:
> SECRET_KEY "xxxxx"
> ALLOWED_OPERATIONS {"provision", "get", "find", "count", "update", "insert", "remove", "select", "delete", "describeDatabase", "finditem", "findSchemas", "listSchemas", "list", "convert", "load", "listbuilds"}
> 
> The container runs on Google Cloud Run, the MySQL database runs on Google SQL Cloud fully managed service, database is working fine and database user has all permissions.
> 
> Any help you can provide is much appreciated.
> 
> Regards,
> 
> Eugene Boulis

Maybe temporary assign a hard coded sql config to `sqlConfig` to make sure mysql.createConnection(sqlConfig) succeeds first? If it does, at least you know the config is correct. 

Next, you want to make sure `JSON.parse(process.env.SQL_CONFIG)` gives you the same config value as the one you just hard coded. You can do that by removing this line  https://github.com/wix/corvid-external-db-mysql-adapter/blob/6c4333c7d8e50e979f89a53913a3aae5a4bdaa80/client/database.js#L5

**Comment by eboulis** [comment]
I am trying to setup a development environment to allow me to troubleshoot and experiment with your suggested settings.

I have cloned the adapter's GitHub repository as per "developing and extending the adapter" instructions here https://github.com/wix/corvid-external-db-mysql-adapter, however I am not sure I understand how this will work, could you please help explaing:

  1.  Why do we need to setup a local MySQL proxy since all we want is to create another version of the adapter which currently runs on Google Cloud Run while the database currently runs on Google MySQL Cloud fully managed, wouldn't the customized connector which I need to create also run on Google Run Cloud Run and connect to the current database?
  2.  How will the wix site connect to the local MySQL proxy, currently I obtain the MySQL adapter service point from Google Cloud Run service details page which shows the URL of the deployed MySQL adapter?
  3.  How to obtain the URL for the locally deployed adapter above?

Thanks for your help.




________________________________

**Comment by happyappledog** [comment]
I am not sure why local MySQL proxy is needed. I am actually using AWS RDS instead, and I can connect to it using its URL directly. Maybe a proxy is specifically required by Google MySQL in general?
The way I debug this is to use the database in the cloud, but host this connector locally. So nothing is changed except that now I am hosting the connector on my laptop instead of Google Cloud.

The local URL will be something like http://localhost:8080 . We can't connect to it from wix, it's just for debugging the codes locally. 

Hope this help.

**Comment by eboulis** [comment]
Thanks this is of great help it helps to clarify how the connector is setup for local development 

Once you have tested it all works and ready to deploy to production, do you create a Github branch off the original repo then push your local changes to the Github branch creating a new Docker MySql adapter container URL which is then deployed to the Google Cloud Run service or can I just deploy straight from my local machine Github clone to Google Cloud Run?

**Comment by happyappledog** [comment]
If after debugging, you know you have the right SQL_CONFIG in the yml file, you don't have to change this adapter codes (unless there is something else you want to modify in the codes), which means you don't need to change the docker container.

If you do need to change the code, as long as you know how to create a docker container, I guess you can just deploy the new container to Cloud Run directly? I didn't try out Cloud Run here but App Engine. For App Engine, you can just deploy straight from your local folder.

**Comment by eboulis** [comment]
Hi, 

Thanks very much to the great help you provided to me, much appreciated.

I am a developer and have developed in J2EE, .Net as well as in C/C++, I have also developed on Windows, Linux and Solaris platforms, but I am totally new to Node.js. To enable me to get this MySQL Wix adapter to work, I have setup a Node.js development environment on my Windows desktop, I have installed NVM for Windows and the latest stable Node.js release.  I have also installed Ubuntu 18.04 running on top of VMware VM Player and I am using VS Code editor for Windows.

Before attempting a full clone on Ubuntu which I have to figure out how to connect to it from Wix (I may have to configure port forwarding to make it work), it would be much simpler if I can make temporary changes to the Node.js code and debug while still using the original docker container, or a clone of the container on a GCP folder, how would I be able to do that I mean make changes to the code in Github while still being able to deploy on Google Cloud Run using the same method ad before?

Again thanks a million for your great help which I am much grateful for.

Regards

Eugene Boulis

**Comment by alex-douglas** [comment]
> I am not sure why local MySQL proxy is needed. I am actually using AWS RDS instead, and I can connect to it using its URL directly. Maybe a proxy is specifically required by Google MySQL in general?
> The way I debug this is to use the database in the cloud, but host this connector locally. So nothing is changed except that now I am hosting the connector on my laptop instead of Google Cloud.
> 
> The local URL will be something like http://localhost:8080 . We can't connect to it from wix, it's just for debugging the codes locally.
> 
> Hope this help.

@happyappledog I am also using an AWS RDS instance and hoping to connect it to my Wix site. Could you provide more details on how you got them connected? When you say you can connect to it directly using its URL do you mean you can literally add the URL to the Wix website builder with no additional development, or did you modify the Adapter template in this repo? If the latter, would love if you could publish your version of the Adapter for AWS RDS to GitHub if possible. Thank you!
