### ISSUE TITLE
Issue creating new items as collection shown as "read-only" despite correct allowed permissions set

### ISSUE THREAD

**Issue by mbiermann** [wix/corvid-external-db-mysql-adapter#18]
Hi,

first of all thank you for creating this boilerplate! I have set up the application following your documentation on Google Cloud Run. 

Despite me having configured all allowed permissions ["get", "find", "count", "update", "insert", "remove"], Wix is now allowing me to create a new item and shows me the collection being "read-only". Updating items I created via a direct connection to the MySQL database works properly. What am I doing wrong here?

On another note I realized that the sandbox and live data displayed in Wix are identical. Is it correct that there is no difference between sandbox and live when using external databases?

Many thanks for your support.

**Comment by mbiermann** [comment]
Update: I checked the logs of the application and found I was missing to provide columns "_createdDate", "_updatedDate" and "_owner" in the table. That solved the issue with the insert. However I can still not add fields as the collection remains "read-only". Any ideas?

**Comment by kkchauhan** [comment]
I am getting same errror

**Comment by mbiermann** [comment]
@kkchauhan It's important that you add _id and _owner columns to your table (with NULL value allowed).

**Comment by kkchauhan** [comment]
Shall I create _createdDate and _updatedDate field too.. Because its still not working for me

**Comment by evgolsh** [comment]
Hey, in order to make mysql collections writable please use the following template when creating MySQL tables:
`
create table your_table(
    _id varchar(128) not null primary key,
    _owner varchar(128),
    _createdDate datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
    _updatedDate datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ....
)
`
