### ISSUE TITLE
provision request fails

### ISSUE THREAD

**Issue by FalkWolsky** [wix/corvid-external-db-mysql-adapter#19]
The only message that is left by the API Call is:

{ "message": "Cannot enqueue Query after fatal error." }

Auth to database is made and connection is working…
Provision-Request seems also ok. I use Postman and send the following configuration as POST body:

{ 
	"requestContext" : {
		"settings" : {
			"secretKey":"<super secret key>"
		}
	}

}

**Comment by evgolsh** [comment]
Hi, please make sure you set correct settings in SQL_CONFIG environment variable. 
It should be in form of 
`{"socketPath":"/cloudsql/[YOUR_SQL_INSTANCE]", "user": "[YOUR_USER]", "password":"[YOUR_PASSWORD]", "database":"DATABASE_YOU_CREATED"}`
